repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.9.1"
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
        exclude: ^examples/
      - id: ruff-format
        exclude: ^examples/
