services:
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=agentops_test
    ports:
      - "5432:5432"
    networks:
      - jaeger-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"   # Jaeger thrift compact protocol (UDP)
      - "6832:6832/udp"   # Jaeger thrift binary protocol (UDP)
      - "5778:5778"       # Jaeger admin port
      - "16686:16686"     # Jaeger UI
      - "4317:4317"       # OTLP gRPC
      - "4318:4318"       # OTLP HTTP
      - "14250:14250"     # Model/collector gRPC
      - "14268:14268"     # Jaeger HTTP thrift collector
      - "14269:14269"     # Admin port
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
    networks:
      - jaeger-net

networks:
  jaeger-net:
    driver: bridge 