exclude = [
    ".*__pycache__",
    ".*egg-info",
    "docs",
    "examples",
    "tests",
    "venv",
]
source_roots = [
    ".",
]

[[modules]]
path = "agentops"
depends_on = [
    { path = "agentops.enums" },
    { path = "agentops.log_config" },
]

[[modules]]
path = "agentops.enums"
depends_on = []

[[modules]]
path = "agentops.log_config"
depends_on = []

[dependency-groups]
ci = [
    "tach~=0.9",
]
