# fly.toml app configuration file generated for agentops-server-next on 2024-03-18T12:59:35-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'agentops-server-next'
primary_region = 'sjc'
swap_size_mb = 512

[build]
  builder = 'paketobuildpacks/builder:base'

[env]
  PORT = '8000'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[deploy]
  wait_timeout = "10m"

[[vm]]
  size = 'performance-4x'
