version: '2'
image_name: fireworks
docker_image: null
conda_env: fireworks
apis:
- agents
- inference
- memory
- safety
- telemetry
providers:
  inference:
  - provider_id: fireworks
    provider_type: remote::fireworks
    config:
      url: "https://api.fireworks.ai/inference"
      api_key: "<FIREWORKS_API_KEY>"
  memory:
  - provider_id: faiss
    provider_type: inline::faiss
    config:
      kvstore:
        type: sqlite
        namespace: null
        db_path: ${env.SQLITE_STORE_DIR:~/.llama/distributions/fireworks}/faiss_store.db
  safety:
  - provider_id: llama-guard
    provider_type: inline::llama-guard
    config: {}
  agents:
  - provider_id: meta-reference
    provider_type: inline::meta-reference
    config:
      persistence_store:
        type: sqlite
        namespace: null
        db_path: ${env.SQLITE_STORE_DIR:~/.llama/distributions/fireworks}/agents_store.db
  telemetry:
  - provider_id: meta-reference
    provider_type: inline::meta-reference
    config: {}
metadata_store:
  namespace: null
  type: sqlite
  db_path: ${env.SQLITE_STORE_DIR:~/.llama/distributions/fireworks}/registry.db
models:
- metadata: {}
  model_id: meta-llama/Llama-3.2-1B-Instruct
  provider_id: null
  provider_model_id: fireworks/llama-v3p2-1b-instruct
shields:
- params: null
  shield_id: meta-llama/Llama-Guard-3-8B
  provider_id: null
  provider_shield_id: null
memory_banks: []
datasets: []
scoring_fns: []
eval_tasks: []