services:
  collector:
    image: otel/opentelemetry-collector:latest
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317"  # OTLP gRPC
      - "4318:4318"  # OTLP HTTP
    depends_on:
      - processing-service

  processing-service:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
    volumes:
      - .:/app

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  celery-worker:
    build: .
    command: celery -A main.celery_app worker --loglevel=info
    depends_on:
      - redis
      - processing-service
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
    volumes:
      - .:/app 