name: Tach Check

on:
  pull_request:
    paths:
      - '**/*.py'
      - '**/*.ipynb'

jobs:
  tach-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'  # Specify the version of Python you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tach

    - name: Run Tach
      run: tach check