name: Tach Check

on:
  workflow_dispatch:
  pull_request:
    paths:
      - '**/*.py'
      - '**/*.ipynb'

jobs:
  tach-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - uses: astral-sh/setup-uv@v4
      with:
        enable-cache: true
        cache-dependency-glob: "**/pyproject.toml"

    - name: Install dependencies
      run: |
        uv sync --group ci

    - name: Run Tach
      run: uvx tach check
